apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    app: backend-feed
spec:
  selector:
    matchLabels:
      app: backend-feed
  replicas: 1
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
      - name: backend-feed
        image: ezraone/udagram-api-feed:v9
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        resources:
          limits:
            cpu: "500m"
            memory: "1024Mi"
          requests:
            cpu: "250m"
            memory: "128Mi"
        envFrom:
          - secretRef:
              name: env-secret
          - configMapRef:
              name: env-config
          - secretRef:
              name: aws-secret
