apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
spec:
  selector:
    matchLabels:
      run: backend-feed
  replicas: 2
  template:
    metadata:
      labels:
        run: backend-feed
    spec:
      containers:
        - name: backend-feed
          image: ezraone/udagram-api-feed:v4
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 1000m
              memory: "128Mi"
            requests:
              cpu: 500m
          env:
            - name: POSTGRES_USERNAME
              value: "ezraone"
            - name: POSTGRES_PASSWORD
              value: "ezraone3"
            - name: POSTGRES_HOST
              value: "database3.c3f1nxdy8pwb.us-east-1.rds.amazonaws.com"
            - name: POSTGRES_DB
              value: "postgres"