apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    app: udagram-api-feed
spec:
  selector:
    matchLabels:
      run: backend-feed
  replicas: 1
  template:
    metadata:
      labels:
        run: backend-feed
    spec:
      containers:
        - name: backend-feed
          image: ezraone/udagram-api-feed:latest
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 1000m
              memory: "128Mi"
            requests:
              cpu: 500m
              memory: "64Mi"
          env:
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: POSTGRES_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: env-secret
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  key: PSTGRES_HOST
                  name: env-configmap
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DB
                  name: env-configmap