apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      run: frontend
  replicas: 1
  template:
    metadata:
      labels:
        run: frontend
    spec:
      containers:
        - name: frontend
          image: ezraone/udagram-frontend:v9
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "1024Mi"
              cpu: "500"
            requests:
              memory: "128Mi"
              cpu: "250"
