apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
spec:
  selector:
    matchLabels:
      run: reverseproxy
  replicas: 1
  template:
    metadata:
      labels:
        run: reverseproxy
    spec:
      containers:
        - name: reverseproxy
          image: ezraone/reverseproxy
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "128Mi"
              cpu: 1000m
            requests:
              memory: "64Mi"
              cpu: 500m